language: ruby
rvm:
  - 1.8.7
  - ree
env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql
before_install:
  - rvm rubygems 1.8.25
before_script:
  - mysql -e 'create database ocw_test'
  - psql -c 'create database ocw_test' -U postgres
  - bundle exec rake --trace db:migrate
