<% raise NotImplementedError, "Sorry, the 'igniteportland' theme is broken, please try using 'bridgepdx'. See README.txt to set the current theme." %>

# Organization running event:
organization: 'Ignite Portland'

# Breadcrumbs that are always visible, each breadcrumb is a name and URI:
breadcrumbs:
  - ['Ignite Portland', 'http://www.igniteportland.com/']
  - ['Proposals', '/proposals/']

# Timezone for dates in this application:
timezone: 'Pacific Time (US & Canada)'
